### ISSUE TITLE
Roadmap for v2.0.0

### ISSUE THREAD

**Issue by martiliones** [martiliones/icon-set-creator#23]
## Features
- [ ] Interactive CLI
- [ ] Support for Android [Monochrome](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) icons
- [ ] Add configuration options to change rounded Android icons
- [ ] Rename bin name from `iconset` to `icon-set-creator`

## Development
- [ ] Fix ESLint errors
- [ ] Fix CI build
- [ ] Migrate to [pnpm](https://pnpm.io/) package manage
